/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.optimizeddiagnosticsystem.view;

/**
 *
 * @author Fail0verflow
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuDiagnosticSystem
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnubSystemMenu = new javax.swing.JMenuBar();
        mnuMedicalStaff = new javax.swing.JMenu();
        mnuAddStaff = new javax.swing.JMenu();
        mnuImRegisterDoctor = new javax.swing.JMenuItem();
        mnuImRegisterNurse = new javax.swing.JMenuItem();
        mnuRemoveStaff = new javax.swing.JMenu();
        mnuItRemoveDoctor = new javax.swing.JMenuItem();
        mnuImRemoveNurse = new javax.swing.JMenuItem();
        mnuClinicalHistories = new javax.swing.JMenu();
        mnuImLogIn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcome to Diagnostic System");

        mnuMedicalStaff.setText("Medical Staff");

        mnuAddStaff.setText("Add new staff");

        mnuImRegisterDoctor.setText("Register a new doctor");
        mnuImRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImRegisterDoctorActionPerformed(evt);
            }
        });
        mnuAddStaff.add(mnuImRegisterDoctor);

        mnuImRegisterNurse.setText("Register a new nurse");
        mnuImRegisterNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImRegisterNurseActionPerformed(evt);
            }
        });
        mnuAddStaff.add(mnuImRegisterNurse);

        mnuMedicalStaff.add(mnuAddStaff);

        mnuRemoveStaff.setText("Remove staff");

        mnuItRemoveDoctor.setText("Remove doctor");
        mnuItRemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItRemoveDoctorActionPerformed(evt);
            }
        });
        mnuRemoveStaff.add(mnuItRemoveDoctor);

        mnuImRemoveNurse.setText("Remove nurse");
        mnuImRemoveNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImRemoveNurseActionPerformed(evt);
            }
        });
        mnuRemoveStaff.add(mnuImRemoveNurse);

        mnuMedicalStaff.add(mnuRemoveStaff);

        mnubSystemMenu.add(mnuMedicalStaff);

        mnuClinicalHistories.setText("Clinical Histories");

        mnuImLogIn.setText("Log In");
        mnuImLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuImLogInActionPerformed(evt);
            }
        });
        mnuClinicalHistories.add(mnuImLogIn);

        mnubSystemMenu.add(mnuClinicalHistories);

        setJMenuBar(mnubSystemMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuImRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImRegisterDoctorActionPerformed
        this.setVisible(false);
        FrmDoctor frmDoctor = new FrmDoctor();
        frmDoctor.setVisible(true);
    }//GEN-LAST:event_mnuImRegisterDoctorActionPerformed

    private void mnuImRegisterNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImRegisterNurseActionPerformed
        this.setVisible(false);
        FrmNurse frmNurse = new FrmNurse();
        frmNurse.setVisible(true);
    }//GEN-LAST:event_mnuImRegisterNurseActionPerformed

    private void mnuItRemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItRemoveDoctorActionPerformed
        this.setVisible(false);
        FrmRemoveStaff frmRemoveStaff = new FrmRemoveStaff();
        frmRemoveStaff.setVisible(true);
    }//GEN-LAST:event_mnuItRemoveDoctorActionPerformed

    private void mnuImRemoveNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImRemoveNurseActionPerformed
        this.setVisible(false);
        FrmRemoveStaff frmRemoveStaff = new FrmRemoveStaff();
        frmRemoveStaff.setVisible(true);
    }//GEN-LAST:event_mnuImRemoveNurseActionPerformed

    private void mnuImLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuImLogInActionPerformed
        this.setVisible(false);
        FrmUserLogIn frmUserLogIn = new FrmUserLogIn();
        frmUserLogIn.setVisible(true);
    }//GEN-LAST:event_mnuImLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu mnuAddStaff;
    private javax.swing.JMenu mnuClinicalHistories;
    private javax.swing.JMenuItem mnuImLogIn;
    private javax.swing.JMenuItem mnuImRegisterDoctor;
    private javax.swing.JMenuItem mnuImRegisterNurse;
    private javax.swing.JMenuItem mnuImRemoveNurse;
    private javax.swing.JMenuItem mnuItRemoveDoctor;
    private javax.swing.JMenu mnuMedicalStaff;
    private javax.swing.JMenu mnuRemoveStaff;
    private javax.swing.JMenuBar mnubSystemMenu;
    // End of variables declaration//GEN-END:variables
}
